name: Devoir 4 - Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Lancer les tests avec couverture
        run: pytest --cov=app --cov-report=xml --cov-report=term tests/

      - name: Analyse SonarQube
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}